<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup Label="ThunderPropagatorPackages">
        <BuildingBlocksPackageId>ThunderPropagator.BuildingBlocks$(PackageIdConfigurationSuffix)$(PackageIdPlatformSuffix)</BuildingBlocksPackageId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="$(BuildingBlocksPackageId)" Version="1.0.1-beta.14" />
    </ItemGroup>    

</Project>
