<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup Label="ThunderPropagatorPackages">
        <BuildingBlocksVersion>1.0.1-beta.26</BuildingBlocksVersion>
        <BuildingBlocksPackageId>ThunderPropagator.BuildingBlocks$(PackageIdConfigurationSuffix)$(PackageIdPlatformSuffix)</BuildingBlocksPackageId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="$(BuildingBlocksPackageId)" Version="$(BuildingBlocksVersion)" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Tests\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Tests\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Tests\**" />
    </ItemGroup>

</Project>
